/**
 * Per-state provider connectivity ledger.
 *
 * Generated by `analysis/state_connectivity.py <state>` into
 * `frontend/public/api/v1/states/<state>-connectivity.json`.
 *
 * The payload answers one question end to end: starting from every
 * practitioner the NDH lists in a state, how far along the chain to a reachable
 * FHIR endpoint can public data actually get, and where does it stop?
 *
 * The bands are the load-bearing part of the contract. They describe method,
 * not confidence-as-a-feeling, and a consumer must never sum them into a single
 * coverage number. `endpoint` and `endpoint_candidate` are separate fields for
 * the same reason: a candidate is a name collision worth a human check, not a
 * link.
 */

export type EndpointBasis = 'ndh' | 'vendor-npi' | 'name-candidate' | null;

export interface ConnectivityFunnelStep {
  step: string;
  count: number;
  pct: number;
  note: string;
  /** Slug of the finding that measures this link, when one exists. */
  finding?: string;
  /**
   * True for rows that are deliberately outside the chain total, so a reader
   * (or a chart) never adds them into coverage.
   */
  excluded_from_total?: boolean;
}

export interface ConnectivityOrg {
  org_id: string;
  npi: string | null;
  name: string | null;
  city: string | null;
  state: string | null;
  practitioners: number;
  /** Resolved endpoint. Present only for `ndh` and `vendor-npi` bases. */
  endpoint: string | null;
  /** Name-matched only. Never a linkage. */
  endpoint_candidate: string | null;
  endpoint_basis: EndpointBasis;
  vendor: string | null;
}

export interface ConnectivityUnlinkedOrg {
  org_id: string;
  npi: string | null;
  name: string | null;
  city: string | null;
  practitioners: number;
  nppes_verify_url: string | null;
}

export interface ConnectivityGraphNode {
  id: string;
  label: string;
  type: 'system' | 'endpoint' | 'vendor';
  practitioners?: number;
  organizations?: number;
  basis?: string;
  /** Systems only. False is the state the picture exists to show. */
  connected?: boolean;
  vendor?: string | null;
  via?: string | null;
}

export interface ConnectivityGraph {
  note: string;
  nodes: ConnectivityGraphNode[];
  links: { source: string; target: string; kind: 'reaches' | 'served-by' }[];
}

export interface ConnectivitySystem {
  system_key: string;
  label: string;
  basis: 'cms-ownership' | 'nppes-parent' | 'brand-name';
  organizations: number;
  practitioners: number;
  member_org_ids: string[];
  endpoint_count: number;
  endpoints: { url: string; vendor: string | null; via_member: string }[];
  vendors: string[];
}

/**
 * One county. Rates are `null` rather than 0 when the denominator does not
 * exist, because a county with no practitioners and a county where nobody
 * reaches an endpoint are different facts and must not share a colour.
 */
export interface ConnectivityCounty {
  fips: string;
  name: string | null;
  population: number | null;
  /** USDA Rural-Urban Continuum Code, 1-3 metro and 4-9 nonmetro. */
  rucc: number | null;
  rural: boolean | null;
  median_household_income: number | null;
  pct_65_plus: number | null;
  practitioners: number;
  with_role: number;
  reaches_endpoint: number;
  role_pct: number | null;
  endpoint_pct: number | null;
  practitioners_per_10k: number | null;
  behavioral_health_pct: number | null;
  physician_pct: number | null;
}

/**
 * One plotted organization. `tier` is the evidence that reached its endpoint,
 * and `null` means nothing public does. The endpoint URL is deliberately not
 * here: see the note in analysis/state_connectivity.py.
 */
export interface ConnectivityGeoOrg {
  name: string | null;
  npi: string | null;
  practitioners: number;
  sites: number | null;
  city: string | null;
  lat: number;
  lng: number;
  vendor: string | null;
  tier: string | null;
}

export interface ConnectivityGeo {
  note: string;
  county_assignment: {
    method: string;
    zips_spanning_more_than_one_county: number;
    zips_where_dominant_county_holds_under_75_pct: number;
    practitioners_with_unmatched_postal_code: number;
  };
  point_layer: {
    unit: string;
    organizations_plotted: number;
    organizations_without_any_geocoded_site: number;
  };
  counties: ConnectivityCounty[];
  organizations: ConnectivityGeoOrg[];
}

/**
 * Two-letter code to state FIPS prefix, for filtering the county atlas.
 * Territories are absent because the us-atlas county file does not carry them.
 */
export const STATE_FIPS: Record<string, string> = {
  AL: '01', AK: '02', AZ: '04', AR: '05', CA: '06', CO: '08', CT: '09',
  DE: '10', DC: '11', FL: '12', GA: '13', HI: '15', ID: '16', IL: '17',
  IN: '18', IA: '19', KS: '20', KY: '21', LA: '22', ME: '23', MD: '24',
  MA: '25', MI: '26', MN: '27', MS: '28', MO: '29', MT: '30', NE: '31',
  NV: '32', NH: '33', NJ: '34', NM: '35', NY: '36', NC: '37', ND: '38',
  OH: '39', OK: '40', OR: '41', PA: '42', RI: '44', SC: '45', SD: '46',
  TN: '47', TX: '48', UT: '49', VT: '50', VA: '51', WA: '53', WV: '54',
  WI: '55', WY: '56',
};

/**
 * Map layers. The spatial layout is constant; only the encoding changes.
 *
 * The discriminator is named `id`, not `k-e-y`. Under the old name gitleaks'
 * generic-api-key rule matched the property, because that word sitting beside
 * a long underscored value looks like a credential to it, and the secret scan
 * failed on a file holding no secret. History is immutable so the original
 * finding stays in the baseline; the rename stops it recurring every time a
 * layer is added.
 *
 * Do not spell the old property name followed by a colon and a quoted value
 * anywhere in this file, including in a comment explaining the problem. The
 * first version of this note quoted it verbatim, reintroduced the exact
 * pattern at a new commit and line, and failed the scan a second time.
 */
export const GEO_LAYERS = [
  {
    id: 'endpoint_pct',
    label: 'Reaches an endpoint',
    unit: '%',
    blurb:
      'Share of the county’s practitioners for whom some public source reaches a FHIR endpoint.',
  },
  {
    id: 'role_pct',
    label: 'Has an affiliation',
    unit: '%',
    blurb:
      'Share carrying an active PractitionerRole. Without one the directory names no organization at all.',
  },
  {
    id: 'practitioners_per_10k',
    label: 'Practitioners per 10k residents',
    unit: '',
    blurb:
      'Supply, not connectivity. Counties hosting a health system’s headquarters run far above their own population.',
  },
  {
    id: 'behavioral_health_pct',
    label: 'Behavioral health share',
    unit: '%',
    blurb:
      'The profession with the largest affiliation gap. Where this is high, directory coverage is structurally worse.',
  },
  {
    id: 'pct_65_plus',
    label: 'Residents 65 and older',
    unit: '%',
    blurb: 'Demand context, from Census population estimates.',
  },
  {
    id: 'median_household_income',
    label: 'Median household income',
    unit: '$',
    blurb: 'Context from USDA ERS.',
  },
] as const;

export type GeoLayerKey = (typeof GEO_LAYERS)[number]['id'];

export interface ConnectivityPayload {
  state: string;
  state_name: string;
  slug: string;
  release_date: string;
  generated_at: string;
  methodology_version: string;
  commit_sha: string;
  summary: {
    practitioners: number;
    with_role: number;
    with_role_pct: number;
    reaches_endpoint: number;
    reaches_endpoint_pct: number;
    reaches_endpoint_ndh_only: number;
    reaches_endpoint_after_vendor_npi_fill: number;
    reaches_endpoint_after_resolution: number;
    /** Cumulative total after the CMS-enrollment tier, which is the headline. */
    reaches_endpoint_after_cms_enrollment: number;
    /** Reachable only through the practitioner's CMS-enrolled group. */
    reaches_endpoint_via_enrollment_only: number;
    /**
     * The subset of the enrollment tier carrying no PractitionerRole at all.
     * The only practitioners any tier reaches without the directory first
     * affiliating them.
     */
    reaches_endpoint_via_enrollment_without_role: number;
    /** with_role plus practitioners affiliated only by CMS enrollment. */
    affiliated_any_source: number;
    reaches_endpoint_pct_of_affiliated: number;
    /**
     * The same rate against the pre-enrollment denominator. Both ship because
     * moving a numerator and a denominator in one release is how a published
     * number stops being comparable to last week's.
     */
    reaches_endpoint_pct_of_ndh_affiliated: number;
    vendor_known: number;
    organizations: number;
    organizations_with_endpoint: number;
    name_matched_candidates: number;
    organizations_with_name_candidate_only: number;
  };
  geo: ConnectivityGeo | null;
  funnel: ConnectivityFunnelStep[];
  confidence: {
    note: string;
    green: number;
    yellow: number;
    resolved: number;
    /** Reached through CMS enrollment rather than through the directory. */
    enrolled: number;
    candidate: number;
    red: number;
    none: number;
  };
  vendors: Record<string, number>;
  organizations_top: ConnectivityOrg[];
  graph: ConnectivityGraph;
  systems: {
    note: string;
    affiliation_graph: {
      note: string;
      edges: number;
      organizations_in_graph: number;
      components: number;
      largest_component_size: number;
      top_hubs: { name: string | null; children: number }[];
    };
    organizations_with_cms_attested_owner: number;
    organizations_with_nppes_parent: number;
    systems_found: number;
    systems_by_basis: Record<string, number>;
    systems_reaching_an_endpoint: number;
    practitioners_in_a_system_that_reaches_an_endpoint: number;
    routing_caveat: string;
    rows: ConnectivitySystem[];
  };
  organizations_unlinked: {
    note: string;
    practitioners_affected: number;
    rows: ConnectivityUnlinkedOrg[];
  };
  hospitals: {
    source_slug: string | null;
    hospitals: number | null;
    in_vendor_bundle: number | null;
    endpoint_resolvable: number | null;
    org_endpoint_linked: number | null;
    critical_access: number | null;
    in_rural_counties: number | null;
    ehr_vendors: Record<string, number> | null;
  } | null;
  sources: Record<string, string | null>;
  limits: string[];
}
