/**
 * Per-state provider connectivity ledger.
 *
 * Generated by `analysis/state_connectivity.py <state>` into
 * `frontend/public/api/v1/states/<state>-connectivity.json`.
 *
 * The payload answers one question end to end: starting from every
 * practitioner the NDH lists in a state, how far along the chain to a reachable
 * FHIR endpoint can public data actually get, and where does it stop?
 *
 * The bands are the load-bearing part of the contract. They describe method,
 * not confidence-as-a-feeling, and a consumer must never sum them into a single
 * coverage number. `endpoint` and `endpoint_candidate` are separate fields for
 * the same reason: a candidate is a name collision worth a human check, not a
 * link.
 */

export type EndpointBasis = 'ndh' | 'vendor-npi' | 'name-candidate' | null;

export interface ConnectivityFunnelStep {
  step: string;
  count: number;
  pct: number;
  note: string;
  /** Slug of the finding that measures this link, when one exists. */
  finding?: string;
  /**
   * True for rows that are deliberately outside the chain total, so a reader
   * (or a chart) never adds them into coverage.
   */
  excluded_from_total?: boolean;
}

export interface ConnectivityOrg {
  org_id: string;
  npi: string | null;
  name: string | null;
  city: string | null;
  state: string | null;
  practitioners: number;
  /** Resolved endpoint. Present only for `ndh` and `vendor-npi` bases. */
  endpoint: string | null;
  /** Name-matched only. Never a linkage. */
  endpoint_candidate: string | null;
  endpoint_basis: EndpointBasis;
  vendor: string | null;
}

export interface ConnectivityUnlinkedOrg {
  org_id: string;
  npi: string | null;
  name: string | null;
  city: string | null;
  practitioners: number;
  nppes_verify_url: string | null;
}

export interface ConnectivityGraphNode {
  id: string;
  label: string;
  type: 'system' | 'endpoint' | 'vendor';
  practitioners?: number;
  organizations?: number;
  basis?: string;
  /** Systems only. False is the state the picture exists to show. */
  connected?: boolean;
  vendor?: string | null;
  via?: string | null;
}

export interface ConnectivityGraph {
  note: string;
  nodes: ConnectivityGraphNode[];
  links: { source: string; target: string; kind: 'reaches' | 'served-by' }[];
}

export interface ConnectivitySystem {
  system_key: string;
  label: string;
  basis: 'cms-ownership' | 'nppes-parent' | 'brand-name';
  organizations: number;
  practitioners: number;
  member_org_ids: string[];
  endpoint_count: number;
  endpoints: { url: string; vendor: string | null; via_member: string }[];
  vendors: string[];
}

export interface ConnectivityPayload {
  state: string;
  state_name: string;
  slug: string;
  release_date: string;
  generated_at: string;
  methodology_version: string;
  commit_sha: string;
  summary: {
    practitioners: number;
    with_role: number;
    with_role_pct: number;
    reaches_endpoint: number;
    reaches_endpoint_pct: number;
    reaches_endpoint_ndh_only: number;
    reaches_endpoint_after_fill: number;
    vendor_known: number;
    organizations: number;
    organizations_with_endpoint: number;
    name_matched_candidates: number;
    organizations_with_name_candidate_only: number;
  };
  funnel: ConnectivityFunnelStep[];
  confidence: {
    note: string;
    green: number;
    yellow: number;
    candidate: number;
    red: number;
    none: number;
  };
  vendors: Record<string, number>;
  organizations_top: ConnectivityOrg[];
  graph: ConnectivityGraph;
  systems: {
    note: string;
    affiliation_graph: {
      note: string;
      edges: number;
      organizations_in_graph: number;
      components: number;
      largest_component_size: number;
      top_hubs: { name: string | null; children: number }[];
    };
    organizations_with_cms_attested_owner: number;
    organizations_with_nppes_parent: number;
    systems_found: number;
    systems_by_basis: Record<string, number>;
    systems_reaching_an_endpoint: number;
    practitioners_in_a_system_that_reaches_an_endpoint: number;
    routing_caveat: string;
    rows: ConnectivitySystem[];
  };
  organizations_unlinked: {
    note: string;
    practitioners_affected: number;
    rows: ConnectivityUnlinkedOrg[];
  };
  hospitals: {
    source_slug: string | null;
    hospitals: number | null;
    in_vendor_bundle: number | null;
    endpoint_resolvable: number | null;
    org_endpoint_linked: number | null;
    critical_access: number | null;
    in_rural_counties: number | null;
    ehr_vendors: Record<string, number> | null;
  } | null;
  sources: Record<string, string | null>;
  limits: string[];
}
