/**
 * Value explorer data contract.
 *
 * Generated by `analysis/explorer_geo.py` into /api/v1/explorer/, one small
 * national index plus one file per state carrying county and ZIP detail.
 *
 * Static by design. A crawlable state -> county -> ZIP drill-down backed by
 * live BigQuery is an unbounded bill: every crawler that walks the tree pays
 * for a scan. Same contract as /npi.
 *
 * Two things in this shape are deliberate and a consumer must not undo them.
 *
 * ORGANIZATIONS ARE NEVER SUMMED. Roughly half the NDH Organization file is
 * `ein` tax records that carry an NPI and an address, so `orgs_provider` and
 * `orgs_ein` describe the same places twice from different angles. Adding them
 * reports about double the organizations that exist. They are separate fields
 * for that reason and the UI keeps them apart.
 *
 * PAYERS HAVE NO GEOGRAPHY. All 27 payer organizations in the release carry no
 * state, city or ZIP. `payer_geography` on the index records that as a
 * measurement so the absence is visible rather than looking like a bug.
 */

export interface ExplorerCategory {
  category: string;
  practitioners: number;
  with_role: number;
  /** Null when the denominator is zero, not zero. */
  role_pct: number | null;
}

export interface ExplorerZip {
  zip: string;
  /** 5-digit county FIPS. Null when no county holds a majority of the ZIP. */
  county_fips: string | null;
  county: string | null;
  practitioners: number;
  with_role: number;
  orgs_provider: number;
  orgs_ein: number;
  locations: number;
  /** Mean of the location points in this ZIP. Seeds a map; not a geocoder. */
  lat: number | null;
  lng: number | null;
  by_category: Record<string, number>;
}

export interface ExplorerCounty {
  county_fips: string | null;
  county: string;
  zip_count: number;
  practitioners: number;
  with_role: number;
  role_pct: number | null;
  orgs_provider: number;
  orgs_ein: number;
  by_category: Record<string, number>;
}

export interface ExplorerStateTotals {
  practitioners: number;
  with_role: number;
  orgs_provider: number;
  orgs_ein: number;
  orgs_other: number;
  locations: number;
  with_coords: number;
}

export interface ExplorerStatePayload {
  state: string;
  release_date: string;
  generated_at: string;
  methodology_version: string;
  totals: ExplorerStateTotals;
  by_category: ExplorerCategory[];
  counties: ExplorerCounty[];
  zips: ExplorerZip[];
  notes: string;
}

export interface ExplorerIndexState {
  state: string;
  practitioners: number;
  with_role: number;
  role_pct: number | null;
  orgs_provider: number;
  orgs_ein: number;
  counties: number;
  zips: number;
  url: string;
}

export interface ExplorerIndex {
  release_date: string;
  generated_at: string;
  methodology_version: string;
  states: ExplorerIndexState[];
  payer_geography: {
    payer_organizations: number;
    with_any_state: number;
    note: string;
  };
  notes: string;
}

/**
 * Metrics the explorer can colour a map by.
 *
 * Every one is a RATE or a per-capita figure, never a raw count. A choropleth
 * of counts is a population map wearing a different hat: it will show you
 * Philadelphia and Allegheny every time, whatever you are actually measuring.
 * Raw counts stay in the table and the side panel, where they belong.
 */
export type ExplorerMetricKey =
  | 'role_pct'
  | 'practitioners_per_10k'
  | 'orgs_per_practitioner'
  | 'behavioral_health_share';

export interface ExplorerMetricDef {
  key: ExplorerMetricKey;
  label: string;
  description: string;
  format: (v: number) => string;
}

export const EXPLORER_METRICS: ExplorerMetricDef[] = [
  {
    key: 'role_pct',
    label: 'Has a workplace',
    description:
      'Share of practitioners the directory says work somewhere. Without it, ' +
      'software cannot get from a clinician to an organization to a records ' +
      'endpoint. This is the binding constraint on the whole chain.',
    format: (v) => `${v.toFixed(1)}%`,
  },
  {
    key: 'behavioral_health_share',
    label: 'Behavioral health share',
    description:
      'Share of listed practitioners in behavioral health. Included because ' +
      'this is the profession the directory describes worst relative to how ' +
      'much care it delivers.',
    format: (v) => `${v.toFixed(1)}%`,
  },
  {
    key: 'orgs_per_practitioner',
    label: 'Organizations per 100 practitioners',
    description:
      'Provider organizations only. `ein` tax records are excluded: they ' +
      'describe the same places again and including them roughly doubles the ' +
      'number.',
    format: (v) => v.toFixed(1),
  },
];
