/**
 * Landscape data contract for /landscape Karpathy-style treemap.
 *
 * Each cell is one (state, specialty_category) tuple. Area on the treemap is
 * scaled by `practitioners`. Each metric value is a 0..1 score where higher = better
 * (e.g. 0.97 completeness, 0.62 reachability) except `currency_days_median`, which
 * is a raw count (lower = better) rendered with an inverted scale.
 *
 * Static JSON contract; generated by analysis/landscape.py. Loaded at build time
 * via loadLandscape() in load-api-v1.ts. External consumers fetch from /api/v1/landscape.json.
 */

export type LandscapeMetricKey =
  | 'completeness'
  | 'cross_source_agreement'
  | 'currency_days_median'
  | 'reachability'
  | 'integrity'
  | 'specialty_validity';

export interface LandscapeCell {
  state: string;
  state_name: string;
  specialty_code: string;
  specialty_display: string;
  practitioners: number;
  metrics: {
    completeness: number;
    cross_source_agreement: number;
    currency_days_median: number;
    reachability: number;
    integrity: number;
    specialty_validity: number;
  };
  sample_npis: string[];
}

export interface LandscapePayload {
  generated_at: string;
  methodology_version: string;
  release: string;
  cell_count: number;
  cells: LandscapeCell[];
  national_baseline: LandscapeCell['metrics'];
}

export interface LandscapeMetricDef {
  key: LandscapeMetricKey;
  label: string;
  description: string;
  invert: boolean;
  format: (v: number) => string;
}

export const LANDSCAPE_METRICS: LandscapeMetricDef[] = [
  {
    key: 'completeness',
    label: 'Completeness',
    description:
      'Share of provider records with every § 6220-required field populated (name, specialty, contact, address, new-patient acceptance, ADA, language, telehealth).',
    invert: false,
    format: (v) => `${(v * 100).toFixed(1)}%`,
  },
  {
    key: 'cross_source_agreement',
    label: 'Cross-source agreement',
    description:
      'Share of practitioners findable in NPPES AND at least one payer FHIR directory AND PECOS. The intersection a plan cannot grade itself on.',
    invert: false,
    format: (v) => `${(v * 100).toFixed(1)}%`,
  },
  {
    key: 'currency_days_median',
    label: 'Currency',
    description:
      'Median days since meta.lastUpdated. The 90-day verification cadence in § 6220 fails above 90.',
    invert: true,
    format: (v) => `${Math.round(v)} days`,
  },
  {
    key: 'reachability',
    label: 'Endpoint reachability',
    description:
      'Share of practitioners whose managing organization has a FHIR endpoint that responds to a live probe (H1–H5).',
    invert: false,
    format: (v) => `${(v * 100).toFixed(1)}%`,
  },
  {
    key: 'integrity',
    label: 'Federal integrity',
    description:
      'Share of practitioners NOT flagged by OIG LEIE, SAM.gov, or NPPES deactivation. Lower means more records with at least one federal flag.',
    invert: false,
    format: (v) => `${(v * 100).toFixed(2)}%`,
  },
  {
    key: 'specialty_validity',
    label: 'Specialty validity',
    description:
      'Share of practitioner_role.specialty codes that resolve cleanly against the NUCC ↔ CMS Medicare crosswalk (H10–H13).',
    invert: false,
    format: (v) => `${(v * 100).toFixed(1)}%`,
  },
];
