/**
 * Types for the Pennsylvania rural hospital connectivity payload.
 *
 * Generated by `analysis/pa_rural_health.py` and served from
 * /api/v1/states/pa-rural-health.json. Shape is part of the public contract.
 */

export interface PaCounty {
  fips: string;
  name: string;
  /** USDA ERS Rural-Urban Continuum Code 2023. 1-3 metro, 4-9 nonmetro. */
  rucc?: number;
  rucc_description?: string;
  /** True when rucc >= 4. */
  rural: boolean;
  population?: number;
  population_2020?: number;
  median_household_income?: number;
  median_age?: number;
  pct_65_plus?: number;
}

export interface PaHospital {
  ccn: string;
  name: string;
  city: string;
  county: string;
  county_fips: string | null;
  zip: string;
  hospital_type: string;
  /** Federal facility-level rural designation. */
  critical_access: boolean;
  ownership: string;
  emergency_services: boolean;
  /** Derived from the facility name only; null when the name carries no brand. */
  health_system: string | null;
  county_rural: boolean;
  county_rucc: number | null;
  /** Appears in a certified-EHR vendor's published service-base-URL bundle. */
  in_cehrt_bundle: boolean;
  /** The Organization resource references an Endpoint resource. */
  org_endpoint_linked: boolean;
  ehr_vendor: string | null;
  vendor_record_synthetic: boolean;
  match_method: 'name_city_exact' | 'name_city_token' | null;
}

export interface PaRuralPayload {
  state: string;
  state_name: string;
  slug: string;
  hypotheses: string[];
  generated_at: string;
  methodology_version: string;
  summary: {
    hospitals: number;
    counties: number;
    rural_counties: number;
    hospitals_in_rural_counties: number;
    critical_access_hospitals: number;
    in_cehrt_bundle: number;
    org_endpoint_linked: number;
    rural_in_cehrt_bundle: number;
    cah_in_cehrt_bundle: number;
    match_exact: number;
    match_token: number;
    match_none: number;
    ehr_vendors: Record<string, number>;
    /** Per-vendor: PA organizations published, and how many cross-link to an Endpoint. */
    vendor_endpoint_linkage?: Record<string, { pa_orgs: number; endpoint_linked: number }>;
  };
  counties: PaCounty[];
  hospitals: PaHospital[];
  connectivity_note: string;
  sources: Record<string, string>;
  limits: string[];
}

/** County overlays the map can colour by. */
export type PaOverlay = 'rural' | 'income' | 'age65' | 'median_age' | 'hospitals';

export const PA_OVERLAYS: {
  key: PaOverlay;
  label: string;
  description: string;
  /** Higher value is worse for the reader (drives the colour direction). */
  higherIsWorse: boolean;
  format: (n: number | undefined) => string;
}[] = [
  {
    key: 'rural',
    label: 'Rural / metro',
    description:
      'USDA Rural-Urban Continuum Code 2023. Codes 4 through 9 are nonmetro counties, the standard county-level rural classification.',
    higherIsWorse: true,
    format: (n) => (n === undefined ? 'n/a' : `RUCC ${n}`),
  },
  {
    key: 'income',
    label: 'Median household income',
    description:
      'USDA ERS county median household income, 2022. Lower income counties tend to carry thinner hospital margins.',
    higherIsWorse: false,
    format: (n) => (n === undefined ? 'n/a' : `$${n.toLocaleString()}`),
  },
  {
    key: 'age65',
    label: 'Share age 65+',
    description:
      'Census Population Estimates, vintage 2023. A higher share of older residents raises inpatient and post-acute demand.',
    higherIsWorse: true,
    format: (n) => (n === undefined ? 'n/a' : `${n.toFixed(1)}%`),
  },
  {
    key: 'median_age',
    label: 'Median age',
    description: 'Census Population Estimates, vintage 2023.',
    higherIsWorse: true,
    format: (n) => (n === undefined ? 'n/a' : `${n.toFixed(1)} yrs`),
  },
  {
    key: 'hospitals',
    label: 'Hospitals in county',
    description:
      'Count of CMS-listed hospitals whose address falls in the county. Counties with none depend on a neighbouring county.',
    higherIsWorse: false,
    format: (n) => (n === undefined ? '0' : `${n}`),
  },
];
