/**
 * Scoreboard shown on /primer.
 *
 * Generated by `analysis/primer_scoreboard.py`. Metrics that an existing
 * finding already publishes are read out of that finding's JSON rather than
 * restated, because a number restated by hand is a number that keeps shipping
 * wrong after the original is corrected.
 */
export interface PrimerMetric {
  key: string;
  label: string;
  /** The plain question the metric answers, for readers who skip the label. */
  question: string;
  /** Null when a metric is registered but not yet measured. */
  value: number | null;
  unit: string;
  detail: string;
  /** Where the number could get to, or what would have to change. */
  headroom: string;
  /** Slug of the finding that produced it, when one exists. */
  finding: string | null;
}

export interface PrimerScoreboard {
  title: string;
  note: string;
  release_date: string;
  generated_at: string;
  commit_sha: string;
  metrics: PrimerMetric[];
}
